[2022-02-12 14:01:06,898] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 14:01:06,954] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 14:01:06,955] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:06,955] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:01:06,959] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:06,987] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2022-02-11T00:00:00+00:00
[2022-02-12 14:01:06,995] {standard_task_runner.py:52} INFO - Started process 4048 to run task
[2022-02-12 14:01:07,018] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2022-02-11T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmp0ctlno9k', '--error-file', '/tmp/tmpx2racttl']
[2022-02-12 14:01:07,024] {standard_task_runner.py:77} INFO - Job 3: Subtask task_3
[2022-02-12 14:01:07,253] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2022-02-11T00:00:00+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:01:07,580] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T00:00:00+00:00
[2022-02-12 14:01:07,581] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:01:07,583] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:01:07,621] {subprocess.py:75} INFO - Output:
[2022-02-12 14:01:10,629] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:01:11,080] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20220211T000000, start_date=20220212T170106, end_date=20220212T170111
[2022-02-12 14:01:11,455] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:01:11,536] {local_task_job.py:151} INFO - Task exited with return code 0
