[2022-02-12 14:01:22,785] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-02-12T17:01:08.870598+00:00 [queued]>
[2022-02-12 14:01:22,808] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-02-12T17:01:08.870598+00:00 [queued]>
[2022-02-12 14:01:22,809] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:22,809] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:01:22,810] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:22,821] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2022-02-12T17:01:08.870598+00:00
[2022-02-12 14:01:22,825] {standard_task_runner.py:52} INFO - Started process 4886 to run task
[2022-02-12 14:01:22,831] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2022-02-12T17:01:08.870598+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmptdo1jjxp', '--error-file', '/tmp/tmp8lgofqc5']
[2022-02-12 14:01:22,834] {standard_task_runner.py:77} INFO - Job 9: Subtask task_4
[2022-02-12 14:01:22,906] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2022-02-12T17:01:08.870598+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:01:23,009] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T17:01:08.870598+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T17:01:08.870598+00:00
[2022-02-12 14:01:23,010] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:01:23,011] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:01:23,018] {subprocess.py:75} INFO - Output:
[2022-02-12 14:01:26,022] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:01:26,076] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20220212T170108, start_date=20220212T170122, end_date=20220212T170126
[2022-02-12 14:01:26,147] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:01:26,180] {local_task_job.py:151} INFO - Task exited with return code 0
