[2021-12-10 16:33:16,874] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-09T00:00:00+00:00 [queued]>
[2021-12-10 16:33:16,905] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-09T00:00:00+00:00 [queued]>
[2021-12-10 16:33:16,906] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 16:33:16,906] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-10 16:33:16,906] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 16:33:16,957] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-12-09T00:00:00+00:00
[2021-12-10 16:33:16,961] {standard_task_runner.py:52} INFO - Started process 3402 to run task
[2021-12-10 16:33:16,970] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-12-09T00:00:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmphwtuexqt', '--error-file', '/tmp/tmpd8_dls8h']
[2021-12-10 16:33:16,979] {standard_task_runner.py:77} INFO - Job 20: Subtask is_api_available
[2021-12-10 16:33:17,224] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-12-09T00:00:00+00:00 [running]> on host ALE-LAPTOP.localdomain
[2021-12-10 16:33:17,476] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-09T00:00:00+00:00
[2021-12-10 16:33:17,477] {http.py:101} INFO - Poking: api/
[2021-12-10 16:33:17,484] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-12-10 16:33:17,487] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-12-10 16:33:18,292] {base.py:243} INFO - Success criteria met. Exiting.
[2021-12-10 16:33:18,309] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211209T000000, start_date=20211210T193316, end_date=20211210T193318
[2021-12-10 16:33:18,379] {local_task_job.py:151} INFO - Task exited with return code 1
